"""add estimated duration to responsibilities

Revision ID: 9d4993fb1d43
Revises: fa28dec56500
Create Date: 2026-07-01 02:29:12.191321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4993fb1d43'
down_revision: Union[str, Sequence[str], None] = 'fa28dec56500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsibilities', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsibilities', 'estimated_duration_minutes')
    # ### end Alembic commands ###
